# Generated by Django 4.2.4 on 2023-08-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alat', '0003_rename_tanggal_ditambahkan_alat_tanggal_aktif'),
    ]

    operations = [
        migrations.CreateModel(
            name='POMPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pompa', models.CharField(blank=True, max_length=40, null=True)),
                ('alat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alat.alat')),
            ],
        ),
    ]
