# Generated by Django 4.2.4 on 2023-08-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
        ('pompa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pompa',
            name='akun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akun.akun'),
        ),
    ]
