# Generated by Django 4.2.4 on 2023-08-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pompa', '0002_pompa_akun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pompa',
            name='akun',
        ),
    ]
