# Generated by Django 4.2.4 on 2023-08-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wadah_air', '0002_wadah_air_akun'),
        ('pompa', '0003_remove_pompa_akun'),
    ]

    operations = [
        migrations.AddField(
            model_name='pompa',
            name='wadah_air',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wadah_air.wadah_air'),
        ),
    ]
