# Generated by Django 4.2.4 on 2023-08-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompa', '0004_pompa_wadah_air'),
    ]

    operations = [
        migrations.AddField(
            model_name='pompa',
            name='jadwal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pompa',
            name='mode',
            field=models.CharField(blank=True, choices=[('jadwal', 'Jadwal'), ('kering', 'Kering')], max_length=6, null=True),
        ),
    ]
