# Generated by Django 4.2.4 on 2023-08-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pompa', '0005_pompa_jadwal_pompa_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pompa',
            name='jadwal',
        ),
        migrations.RemoveField(
            model_name='pompa',
            name='mode',
        ),
    ]
