# Generated by Django 4.2.4 on 2023-08-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WADAH_AIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_wadah', models.CharField(blank=True, max_length=40, null=True)),
                ('maks_liter', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
