# Generated by Django 4.2.4 on 2023-08-10 22:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TANAMAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tanaman', models.CharField(blank=True, max_length=40, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal_menanam', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('alat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alat.alat')),
            ],
        ),
    ]
