# Generated by Django 4.2.4 on 2023-08-12 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tanaman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanaman',
            name='tanggal_aktif',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tanaman',
            name='tanggal_menanam',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
