# Generated by Django 4.2.4 on 2023-08-12 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pompa', '0004_pompa_wadah_air'),
        ('tanaman', '0003_alter_tanaman_tanggal_menanam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanaman',
            name='alat',
        ),
        migrations.AddField(
            model_name='tanaman',
            name='pompa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pompa.pompa'),
        ),
    ]
