# Generated by Django 4.2.4 on 2023-08-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanaman', '0005_tanaman_jadwal_tanaman_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanaman',
            name='min_kelembapan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
