# Generated by Django 4.2.4 on 2023-08-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanaman', '0008_penjadwalan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanaman',
            name='mode',
            field=models.CharField(blank=True, choices=[('jadwal', 'Jadwal'), ('lembab', 'Kelembapan')], max_length=6, null=True),
        ),
    ]
