# Generated by Django 4.2.4 on 2023-08-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanaman', '0009_tanaman_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanaman',
            name='mode',
            field=models.CharField(choices=[('lembab', 'Kelembapan'), ('jadwal', 'Jadwal')], default='lembab', max_length=6, null=True),
        ),
    ]
