# Generated by Django 4.2.4 on 2023-08-14 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
        ('tanaman', '0011_alter_tanaman_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjadwalan',
            name='akun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akun.akun'),
        ),
    ]
