# Generated by Django 4.2.4 on 2023-08-14 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanaman', '0012_penjadwalan_akun'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjadwalan',
            name='jam',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='penjadwalan',
            name='menit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
    ]
