# Generated by Django 4.2.4 on 2023-08-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanaman', '0013_penjadwalan_jam_penjadwalan_menit'),
    ]

    operations = [
        migrations.CreateModel(
            name='JENIS_TANAMAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenis', models.CharField(blank=True, max_length=40, null=True)),
                ('waktu_panen', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tanaman',
            name='jenis_tanaman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tanaman.jenis_tanaman'),
        ),
    ]
