# Generated by Django 4.2.4 on 2023-08-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
        ('tanaman', '0014_jenis_tanaman_tanaman_jenis_tanaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanaman',
            name='akun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='akun.akun'),
        ),
    ]
