# Generated by Django 4.2.4 on 2023-08-13 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wadah_air', '0002_wadah_air_akun'),
        ('tanaman', '0004_remove_tanaman_alat_tanaman_pompa'),
        ('alat', '0003_rename_tanggal_ditambahkan_alat_tanggal_aktif'),
    ]

    operations = [
        migrations.CreateModel(
            name='MONITORING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelembapan', models.IntegerField(blank=True, null=True)),
                ('tingkat_air', models.IntegerField(blank=True, null=True)),
                ('siram', models.BooleanField(blank=True, default=False, null=True)),
                ('penggunaan_air', models.IntegerField(blank=True, null=True)),
                ('waktu', models.DateTimeField(blank=True, null=True)),
                ('alat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alat.alat')),
                ('tanaman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tanaman.tanaman')),
                ('wadah_air', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wadah_air.wadah_air')),
            ],
        ),
    ]
