# Generated by Django 4.2.4 on 2023-08-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoring',
            name='alat',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='wadah_air',
        ),
    ]
