# Generated by Django 4.2.4 on 2023-08-10 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alat', models.CharField(blank=True, max_length=40, null=True)),
                ('mac_esp', models.CharField(blank=True, max_length=20, null=True)),
                ('ssid', models.CharField(blank=True, max_length=40, null=True)),
                ('akun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akun.akun')),
            ],
        ),
    ]
