# Generated by Django 4.2.4 on 2023-08-10 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alat',
            name='tanggal_ditambahkan',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
