# Generated by Django 4.2.4 on 2023-08-14 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tanaman', '0013_penjadwalan_jam_penjadwalan_menit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PANEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suhu', models.IntegerField(blank=True, null=True)),
                ('jumlah_air', models.IntegerField(blank=True, null=True)),
                ('kelembapan', models.IntegerField(blank=True, null=True)),
                ('status_panen', models.BooleanField(blank=True, null=True)),
                ('tanaman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanaman.tanaman')),
            ],
        ),
    ]
