# Generated by Django 4.2.4 on 2023-08-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanaman', '0014_jenis_tanaman_tanaman_jenis_tanaman'),
        ('panen', '0002_rename_panen_prediksi_panen'),
    ]

    operations = [
        migrations.CreateModel(
            name='HASIL_PANEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_buah', models.IntegerField(blank=True, null=True)),
                ('tanggal_panen', models.DateField(blank=True, null=True)),
                ('tanaman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanaman.tanaman')),
            ],
        ),
    ]
